from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import json
import os 

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)



POKEMAP = {
    "rescue": {
        "Fuerte": {"m": "Charmander", "f": "Pikachu", "text": "Eres una persona... con carácter. Haces la tarea con tesón, y sabes comer muy bien. Tienes una fuerza de voluntad que te permite hacer cosas difíciles. Pero puedes ser cabezota hasta pelearte con tus amigos... Si te enfadas, todo te parece mal, así que aprende a reírte. Alguien con tu carácter puede ser..."},
        "Dócil": {"m": "Bulbasaur", "f": "Chikorita", "text": "Eres una persona... amable. Tienes muy buen corazón. Eres servicial. Haces amistad con todo el mundo. Eres un encanto. Mmm... ¿me estoy pasando? No creo. Tú, mejor que nadie, deberías saberlo. Alguien así puede ser..."},
        "Audaz": {"m": "Machop", "f": "Charmander", "text": "Eres una persona... valiente. Tienes gran sentido de la justicia. Detestas a los malos. No tienes miedo a nadie. ¡Eres un ejemplo a seguir! ¡Adelante! Por la justicia... Por la paz en la tierra... ¡Acaba con las fuerzas del Mal! Mmm... Y, si no he acertado..., ¡procura hacerlo de todos modos! Alguien así puede ser..."},
        "Alegre": {"m": "Squirtle", "f": "Totodile", "text": "Eres una persona... alegre. Siempre estás riéndote y sonriendo, y animando a todo el mundo. ¡Te encanta bromear! Tienes un montón de amigos y todo el mundo te conoce. Aunque, a veces, te dejas llevar y dices cosas que no debes. Tienes que aprender a pensar antes de hablar o actuar. Alguien así puede ser..."},
        "Agitada": {"m": "Pikachu", "f": "Cubone", "text": "Eres una persona... inquieta. No paras, te encanta pasarlo bien, y eres muy bromista. Además tienes un corazón de oro. Por eso todo el mundo te encuentra irresistible. ¡Seguro que no hay nadie tan popular como tú! ¿Cómo? ¿Que no eres tan popular? Será cuestión de modestia... o de que no te has dado cuenta. Igual a la gente le da corte mostrarte sus sentimientos. ¡Pero seguro que muchas personas están deseando decirte que te adoran! Alguien como tú puede ser..."},
        "Ingenua": {"m": "Totodile", "f": "Eevee", "text": "Eres una persona... inocente. Todo te resulta curioso y te encantan las cosas raras. A la gente le hace mucha gracia la actitud desenfadada y alegre que tienes ante las cosas. Pero tienes un defecto. Y es que puedes ser algo infantil. No aguantas nada en los sitios. Siempre vas de aquí para allá. A veces eres egoísta... Procura no serlo tanto. Alguien como tú podría ser..."},
        "Miedosa":{"m": "Cyndaquil", "f": "Mudkip", "text": "Eres una persona algo asustadiza. Por la noche, te lo piensas si tienes que levantarte para ir al baño. Si alguna vez se te olvida algo en el colegio, también te da miedo volver a buscarlo. Cuando tienes que pasar por una calle oscura por la noche, miras hacia atrás de vez en cuando. ¡Pero tener un poco de miedo también tiene su lado bueno! Porque quienes conocen el miedo, saben lo que es ser valiente. Alguien así podría ser..."},
        "Activa": {"m": "Torchic", "f": "Skitty", "text": "Eres una persona... impaciente. Te encanta ocuparte de todo y acabar las cosas. Te lanzas a por todas. Pero, ¿no tienes estrés? Cuando tus amigos no son puntuales, te enfadas. Te molesta que las cosas no salgan como esperas. Eres capaz de machacar el botón del ascensor si tarda mucho. Igual estás pulsando ahora mismo el Botón A sin parar... Pues que sepas que tener un poco de calma es muy saludable. Alguien así puede ser..."},
        "Grosera": {"m": "Treecko", "f": "Torchic", "text": "Eres una persona... descarada. Sueles desconfiar de los demás. Aunque, a pesar de todo, los demás te tienen simpatía de algún modo. Aun así, ¿haces comentarios arrogantes que molestan a la gente? ¿Sueles hacer cosas así? ¿Te caracterizas por tu vanidad, prepotencia y egoísmo? ¿Es lo que dice la gente de ti? ¿Mmm? ¿Que me vaya a paseo? Pero, oye... ¡Dímelo a la cara! (!) Eh... Perdona... Me he pasado tres pueblos. Lo lamento, de verdad. En fin, lo cierto es que eres distante y vas a tu bola. Eres un poco intransigente, pero tienes carisma. Alguien así puede ser..."},
        "Serena": {"m": "Mudkip", "f": "Bulbasaur", "text": "Eres una persona... tranquila. Eres capaz de dar consejo a tus amigos cuando tienen problemas. No te gustan las peleas. Tienes buenos sentimientos y consideración. Debes de tener muchos amigos que te adoran. Aunque... te confías demasiado. A veces no te piensas las cosas... Y haces alguna que otra chapuza. Piensa lo que te he dicho. Alguien así puede ser..."},
        "Plácida": {"m": "Psyduck", "f": "Squirtle", "text": "Eres una persona... algo tranquilota. ¿Te distraes con frecuencia y pierdes el autobús? ¿Te duermes así, de repente? ¿Tardas en reaccionar más que los demás? Bueno, tampoco es que sea malo. Puedes hacer las cosas a tu ritmo, no hace falta que corras. Está bien que vivas de forma reposada, sin complicaciones. Creo que es hasta envidiable. Debes de ser más que popular. Siempre estás con la mirada perdida en el horizonte... Eso llama la atención a cualquiera. Alguien así puede ser..."},
        "Huraña": {"m": "Cubone", "f": "Psyduck", "text": "Eres una persona... solitaria. Siempre te muestras alegre y entusiasta con los demás. Pero eso es cuando estás con gente. Porque cuando no te ve nadie... ¿No te vienes como abajo? Quizá por eso te encuentras tan bien cuando tienes compañía. Pero, si te sientes tan triste, ¡tu organismo sufre! ¡Y tienes que comer más verdura! En fin... Tampoco es tan malo que te sientas así. Cuando estás triste, valoras lo que significa estar con gente. ¡Y así te sientes en compañía! Alguien como tú puede ser..."},
        "Rara": {"m": "Meowth", "f": "Treecko", "text": "Eres una persona... extravagante. Dicen que te caracterizas por una gran excentricidad. Tienes tus manías. Haces cosas con cierta dejadez, pero tienes atractivo. Aunque eres algo infantil... Eres inconstante y eso les causa problemas a los que te rodean. Hasta llegan a enfadarse contigo por eso, ¿a que sí? Si ves que te comportas así, mejor piénsate las cosas antes de hacerlas. Alguien como tú podría ser..."}
    },

    "explorers": {
        "Fuerte": {"m": "Torchic", "f": "Treecko", "text": "Eres una persona... ¡fuerte! Con mucho carácter y determinación. No te lamentas y eres autosuficiente. También eres responsable. Trabajas para lograr tus objetivos y siempre por tus propios medios. Solo necesitas tu empeño para lograr tus objetivos. ¡Pero ten cuidado! ¡Te agotarás si trabajas demasiado por tu cuenta! Deberías admitir que a veces es necesaria la ayuda de los amigos. Alguien con tu carácter podría ser..."},
        "Dócil": {"m": "Charmander", "f": "Bulbasaur", "text": "Eres una persona... ¡dócil! Y muy sensible. Escuchas con atención y respeto, y entiendes rápido las cosas. Como sabes escuchar, tus amigos a menudo te confían sus problemas y preocupaciones. La gente tal vez se burle de ti por tu seriedad y por no saber entender una broma. Seguro que al principio te sorprendes y se te suben los colores, pero después... ¡te unes a sus risas! Alguien dócil y sensible como tú podría ser..."},
        "Osada": {"m": "Pikachu", "f": "Charmander", "text": "Eres una persona... ¡valiente! ¡No sabes lo que es el miedo! Ni temes afrontar el peligro. La justicia es importante para ti y siempre ayudas a la gente en apuros. Pero a veces te pasas un poco con tu sentido de lo correcto... ¡Sé un poco más flexible! Alguien valiente como tú podría ser..."},
        "Alegre": {"m": "Totodile", "f": "Munchlax", "text": "Eres una persona... ¡alegre! Tienes mucho sentido del humor y enseguida te compenetras con los demás. Haces reír a todo el mundo. ¡Muestras una actitud alegre y tienes una vitalidad que anima a cualquiera! Aunque a veces también lloras... De hecho, alternas con facilidad risas y lágrimas... ¡Menudo reto ser así! La vida tiene que ser una sorpresa tras otra. Alguien alegre como tú podría ser..."},
        "Agitada": {"m": "Piplup", "f": "Chimchar", "text": "Eres una persona... ¡traviesa! ¡Cómo te gusta jugar con todo! ¡Y comer bien! Te encanta competir, pero no te gusta perder. Tu personalidad es transparente. Contigo, ¡ya se sabe lo que hay! Alegras a los demás con tu gran sonrisa. A veces temes mostrarte como eres y expresar tus sentimientos. No te lo guardes todo para ti. Pide consejo a tus amigos si lo necesitas. Alguien como tú podría ser..."},
        "Ingenua": {"m": "Chimchar", "f": "Skitty", "text": "Eres una persona... ¡ingenua! ¡Abierta e inocente! ¡También te suele picar la curiosidad! Das tu opinión siempre con naturalidad y dices exactamente lo que piensas. Tienes espíritu artístico y no te frenan las convenciones sociales. Asombras a la gente con tu espontaneidad. Si te pasas, a la gente puede costarle seguirte el ritmo... ¿Has notado que te miran de una manera rara? ¿Sin razón aparente? Alguien inocente como tú podría ser..."},
        "Miedosa": {"m": "Cyndaquil", "f": "Turtwig", "text": "Eres una persona... tímida. ¡Eres muy dulce! A veces sientes vergüenza, ¿verdad? E incluso puedes perderte nuevas experiencias porque la novedad es un reto para ti. Pero no siempre es malo ser prudente, ¿verdad? Al fin y al cabo, te mantiene a salvo. Vives la vida a tu ritmo, ¡sin prisas ni preocupaciones! Alguien como tu podría ser..."},
        "Activa": {"m": "Skitty", "f": "Pikachu", "text": "Eres una persona... ¡impaciente! ¡Hablas deprisa! ¡Comes deprisa! ¡Siempre a todo correr! ¡Todos piensan que trabajas mucho porque nunca te paras! Pero ten cuidado. Si te apresuras tanto, puedes equivocarte más a menudo que los demás. ¡Y sería una pena! ¡Relájate de vez en cuando! ¡Coge aire! Alguien impaciente como tú podría ser..."},
        "Grosera": {"m": "Meowth", "f": "Totodile", "text": "Eres una persona... ¡atrevida! ¡O al menos a veces! No te gustan las órdenes. Eres un poco rebelde y te gusta llevar la contraria. ¡Eres un poco como un lobo solitario! Te gusta hacer las cosas por tu cuenta sin tener que estar pendiente de nadie. La gente mayor puede pensar que eres algo insolente e incluso egoísta. La gente joven, sin embargo, ¡te admira! Alguien como tú podría ser..."},
        "Serena": {"m": "Chikorita", "f": "Cyndaquil", "text": "Eres una persona... ¡tranquila! Tienes gran consideración y antepones siempre el bienestar de tus amigos al tuyo. Tu bondad y generosidad te permiten reírte, perdonar y olvidar los errores de tus amigos. ¡Ve con cuidado! ¡Tu forma de ser puede relegarte demasiado! Alguien tranquilo como tú podría ser..."},
        "Plácida": {"m": "Munchlax", "f": "Meowth", "text": "Eres una persona... ¡relajada! Eres informal, sin apenas preocupaciones. No te gusta correr ni estresarte, y nada te preocupa en exceso. ¡Te encanta sentarte y relajarte! ¡Y tanto! Tienes una personalidad bastante acomodadiza. ¡La gente acude a ti porque le gusta tu forma de ser! Alguien como tú podría ser..."},
        "Huraña": {"m": "Bulbasaur", "f": "Mudkip", "text": "Eres una persona... solitaria, ¡o al menos a veces! ¿Por qué te sorprendes? ¿Acaso no es cierto? Pero, ya sabes lo que dicen... En el fondo todos necesitamos nuestro espacio. Aunque no mucha gente lo reconoce. Así que no lo vayas diciendo por ahí. Si hay algo que nos une... ¡es que todos tenemos que estar solos a veces! Alguien como tú podría ser..."},
        "Rara": {"m": "Squirtle", "f": "Piplup", "text": "Eres una persona... ¡extravagante! ¡Te encanta ir siempre a la moda! Siempre quieres tener lo último, ¿verdad? ¡Te aburres de lo viejo y solo quieres cosas nuevas! Eres fiel a tus emociones y sigues siempre tu voluntad. A la gente le cuesta entender que cambies tan rápido. Tal vez deberías reflexionar sobre cómo tus palabras y actos afectan a los demás. Alguien extravagante como tú podría ser..."},
        "Mansa": {"m": "Treecko", "f": "Chikorita", "text": "Eres una persona... ¡callada! ¡Y muy calmada! Se te dan bien los números y siempre analizas la situación antes de tomar una decisión. Pocas veces te equivocas, ya que decides con calma y tras razonar las cosas con lógica. A veces te cuesta saber lo que piensan los demás y la gente piensa que eres un poco insensible. Deberías expresar más tus sentimientos. Alguien como tú podría ser..."},
        "Alocada": {"m": "Mudkip", "f": "Torchic", "text": "Eres una persona... impulsiva. A veces, hasta un poco impaciente. Más de una vez has salido de casa y se te ha olvidado cerrar la puerta con llave. Y no haces más que perder paraguas. ¡Incluso hasta puedes haber salido a la calle en zapatillas de andar por casa! ¡Y qué me dices de las camisetas del revés! Bueno, ¡igual eso ha sido demasiado! ¡Perdona! ¡Que sepas que a tus amigos les encanta esta faceta tuya! Alguien como tú podría ser... ¡Espera! ¡Otra cosa! ¡A veces cuentas los secretos de tus amigos sin querer! ¡Perdona, pero tenía que decírtelo! Como iba diciendo...alguien como tú podría ser..."},
        "Audaz": {"m": "Turtwig", "f": "Squirtle", "text": "Eres una persona... ¡audaz! ¡Eres tan valiente que nunca te echas atrás! Aunque, a veces, tu osadía te hace pasarte un poco de la raya. No te da vergüenza llevarte a casa las sobras de la cena en el restaurante, ¿verdad? Si alguien te invita a cenar, ¡no te da ningún reparo pedir un montón de comida! No te desconcierta hacer cosas que otros se pensarían dos veces. ¡A veces ni te enteras de que has decepcionado a alguien! Tienes potencial para ser una gran persona... ¡porque nunca te rindes! Alguien audaz como tú podría ser..."}
    },
    "sky": {
        "Fuerte": {"m": "Torchic", "f": "Treecko", "text": "Eres una persona... ¡fuerte! Con mucho carácter y determinación. No te lamentas y eres autosuficiente. También eres responsable. Trabajas para lograr tus objetivos y siempre por tus propios medios. Solo necesitas tu empeño para lograr tus objetivos. ¡Pero ten cuidado! ¡Te agotarás si trabajas demasiado por tu cuenta! Deberías admitir que a veces es necesaria la ayuda de los amigos. Alguien con tu carácter podría ser..."},
        "Dócil": {"m": "Charmander", "f": "Bulbasaur", "text": "Eres una persona... ¡dócil! Y muy sensible. Escuchas con atención y respeto, y entiendes rápido las cosas. Como sabes escuchar, tus amigos a menudo te confían sus problemas y preocupaciones. La gente tal vez se burle de ti por tu seriedad y por no saber entender una broma. Seguro que al principio te sorprendes y se te suben los colores, pero después... ¡te unes a sus risas! Alguien dócil y sensible como tú podría ser..."},
        "Osada": {"m": "Pikachu", "f": "Charmander", "text": "Eres una persona... ¡valiente! ¡No sabes lo que es el miedo! Ni temes afrontar el peligro. La justicia es importante para ti y siempre ayudas a la gente en apuros. Pero a veces te pasas un poco con tu sentido de lo correcto... ¡Sé un poco más flexible! Alguien valiente como tú podría ser..."},
        "Alegre": {"m": "Totodile", "f": "Eevee", "text": "Eres una persona... ¡alegre! Tienes mucho sentido del humor y enseguida te compenetras con los demás. Haces reír a todo el mundo. ¡Muestras una actitud alegre y tienes una vitalidad que anima a cualquiera! Aunque a veces también lloras... De hecho, alternas con facilidad risas y lágrimas... ¡Menudo reto ser así! La vida tiene que ser una sorpresa tras otra. Alguien alegre como tú podría ser..."},
        "Agitada": {"m": "Piplup", "f": "Chimchar", "text": "Eres una persona... ¡traviesa! ¡Cómo te gusta jugar con todo! ¡Y comer bien! Te encanta competir, pero no te gusta perder. Tu personalidad es transparente. Contigo, ¡ya se sabe lo que hay! Alegras a los demás con tu gran sonrisa. A veces temes mostrarte como eres y expresar tus sentimientos. No te lo guardes todo para ti. Pide consejo a tus amigos si lo necesitas. Alguien como tú podría ser..."},
        "Ingenua": {"m": "Chimchar", "f": "Skitty", "text": "Eres una persona... ¡ingenua! ¡Abierta e inocente! ¡También te suele picar la curiosidad! Das tu opinión siempre con naturalidad y dices exactamente lo que piensas. Tienes espíritu artístico y no te frenan las convenciones sociales. Asombras a la gente con tu espontaneidad. Si te pasas, a la gente puede costarle seguirte el ritmo... ¿Has notado que te miran de una manera rara? ¿Sin razón aparente? Alguien inocente como tú podría ser..."},
        "Miedosa": {"m": "Cyndaquil", "f": "Turtwig", "text": "Eres una persona... tímida. ¡Eres muy dulce! A veces sientes vergüenza, ¿verdad? E incluso puedes perderte nuevas experiencias porque la novedad es un reto para ti. Pero no siempre es malo ser prudente, ¿verdad? Al fin y al cabo, te mantiene a salvo. Vives la vida a tu ritmo, ¡sin prisas ni preocupaciones! Alguien como tu podría ser..."},
        "Activa": {"m": "Shinx", "f": "Pikachu", "text": "Eres una persona... ¡impaciente! ¡Hablas deprisa! ¡Comes deprisa! ¡Siempre a todo correr! ¡Todos piensan que trabajas mucho porque nunca te paras! Pero ten cuidado. Si te apresuras tanto, puedes equivocarte más a menudo que los demás. ¡Y sería una pena! ¡Relájate de vez en cuando! ¡Coge aire! Alguien impaciente como tú podría ser..."},
        "Grosera": {"m": "Riolu", "f": "Totodile", "text": "Eres una persona... ¡atrevida! ¡O al menos a veces! No te gustan las órdenes. Eres un poco rebelde y te gusta llevar la contraria. ¡Eres un poco como un lobo solitario! Te gusta hacer las cosas por tu cuenta sin tener que estar pendiente de nadie. La gente mayor puede pensar que eres algo insolente e incluso egoísta. La gente joven, sin embargo, ¡te admira! Alguien como tú podría ser..."},
        "Serena": {"m": "Chikorita", "f": "Cyndaquil", "text": "Eres una persona... ¡tranquila! Tienes gran consideración y antepones siempre el bienestar de tus amigos al tuyo. Tu bondad y generosidad te permiten reírte, perdonar y olvidar los errores de tus amigos. ¡Ve con cuidado! ¡Tu forma de ser puede relegarte demasiado! Alguien tranquilo como tú podría ser..."},
        "Plácida": {"m": "Phanpy", "f": "Vulpix", "text": "Eres una persona... ¡relajada! Eres informal, sin apenas preocupaciones. No te gusta correr ni estresarte, y nada te preocupa en exceso. ¡Te encanta sentarte y relajarte! ¡Y tanto! Tienes una personalidad bastante acomodadiza. ¡La gente acude a ti porque le gusta tu forma de ser! Alguien como tú podría ser..."},
        "Huraña": {"m": "Bulbasaur", "f": "Mudkip", "text": "Eres una persona... solitaria, ¡o al menos a veces! ¿Por qué te sorprendes? ¿Acaso no es cierto? Pero, ya sabes lo que dicen... En el fondo todos necesitamos nuestro espacio. Aunque no mucha gente lo reconoce. Así que no lo vayas diciendo por ahí. Si hay algo que nos une... ¡es que todos tenemos que estar solos a veces! Alguien como tú podría ser..."},
        "Rara": {"m": "Squirtle", "f": "Piplup", "text": "Eres una persona... ¡extravagante! ¡Te encanta ir siempre a la moda! Siempre quieres tener lo último, ¿verdad? ¡Te aburres de lo viejo y solo quieres cosas nuevas! Eres fiel a tus emociones y sigues siempre tu voluntad. A la gente le cuesta entender que cambies tan rápido. Tal vez deberías reflexionar sobre cómo tus palabras y actos afectan a los demás. Alguien extravagante como tú podría ser..."},
        "Mansa": {"m": "Treecko", "f": "Chikorita", "text": "Eres una persona... ¡callada! ¡Y muy calmada! Se te dan bien los números y siempre analizas la situación antes de tomar una decisión. Pocas veces te equivocas, ya que decides con calma y tras razonar las cosas con lógica. A veces te cuesta saber lo que piensan los demás y la gente piensa que eres un poco insensible. Deberías expresar más tus sentimientos. Alguien como tú podría ser..."},
        "Alocada": {"m": "Mudkip", "f": "Torchic", "text": "Eres una persona... impulsiva. A veces, hasta un poco impaciente. Más de una vez has salido de casa y se te ha olvidado cerrar la puerta con llave. Y no haces más que perder paraguas. ¡Incluso hasta puedes haber salido a la calle en zapatillas de andar por casa! ¡Y qué me dices de las camisetas del revés! Bueno, ¡igual eso ha sido demasiado! ¡Perdona! ¡Que sepas que a tus amigos les encanta esta faceta tuya! Alguien como tú podría ser... ¡Espera! ¡Otra cosa! ¡A veces cuentas los secretos de tus amigos sin querer! ¡Perdona, pero tenía que decírtelo! Como iba diciendo...alguien como tú podría ser..."},
        "Audaz": {"m": "Turtwig", "f": "Squirtle", "text": "Eres una persona... ¡audaz! ¡Eres tan valiente que nunca te echas atrás! Aunque, a veces, tu osadía te hace pasarte un poco de la raya. No te da vergüenza llevarte a casa las sobras de la cena en el restaurante, ¿verdad? Si alguien te invita a cenar, ¡no te da ningún reparo pedir un montón de comida! No te desconcierta hacer cosas que otros se pensarían dos veces. ¡A veces ni te enteras de que has decepcionado a alguien! Tienes potencial para ser una gran persona... ¡porque nunca te rindes! Alguien audaz como tú podría ser..."},
    }
}

@app.get("/questions/{test_id}")
async def get_questions(test_id: str):
    try:
        base_path = os.path.dirname(__file__)
        file_path = os.path.join(base_path, "data", f"{test_id}.json")
        print(f"Intentando abrir: {file_path}")
        if not os.path.exists(file_path):
            raise HTTPException(status_code=404, detail=f"Archivo no encontrado")
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
            
    except Exception as e:
        print(f"Error crítico: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/calculate-nature")
async def calculate_nature(results: dict):
    scores = results.get("scores", {})
    gender = results.get("gender", "m")
    test_id = results.get("testId", "rescue")
    if not scores:
        return {"nature": "Desconocida", "pokemon": "MissingNo", "text": "..."}
    nature = max(scores, key=scores.get)
    game_data = POKEMAP.get(test_id, {})
    nature_info = game_data.get(nature, {})
    poke = nature_info.get(gender, "Pikachu")
    desc = nature_info.get("text", "Sos rarito dude")
    return {
        "nature": nature,
        "pokemon": poke,
        "text": desc,
        #"imageURL": f"https://play.pokemonshowdown.com/sprites/ani/{poke.lower()}.gif"
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
